// ---------------------------
// This file was generated by Nango (v0.58.6)
// You can version this file
// ---------------------------

export interface ContentNode {
  type: string;
  content: string;
  startTime: string;
  endTime: string;
  startOffsetMs: number;
  endOffsetMs: number;
  children: 'array<ContentNode>';
  speakerName: string;
  speakerIdentifier: string;
};

export interface LifelogBase {
  id: string;
  title: string;
  markdown: string;
  contents: 'array<ContentNode>';
  startTime: string;
  endTime: string;
};

export interface LifelogList {
  id: string;
  data: 'array<LifelogBase>';
};

export interface LifelogSingle {
  id: string;
  data: LifelogBase;
};

export interface MetaLifelogs {
  nextCursor: string;
  count: number;
};

export interface Meta {
  lifelogs: MetaLifelogs;
};

export interface LifelogsResponseData {
  lifelogs: 'array<LifelogBase>';
};

export interface LifelogsResponse {
  data: LifelogsResponseData;
  meta: Meta;
};
